import { Inter } from "next/font/google";
import Navbar from "./component/Navbar/Navbar";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

 const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <ToastContainer
              hideProgressBar
            />
        {children}
      </body>
    </html>
  );
}

export const notify = (data, interval = 5000) => {
  console.log(data);
  return toast(
    (t) => (
      <div className="emai_toast">
        <div style={{ display: "flex", alignItems: "center" }}>
          {data.type === "success" && (
            <React.Fragment>
              <TickIcon />
              <p className="toast_msg_">{data?.msg}</p>
            </React.Fragment>
          )}
          {data.type === "error" && (
            <React.Fragment>
              <CloseIcon {...{ width: 34, height: 34 }} />
              <p className="toast_msg_">{data?.msg}</p>
            </React.Fragment>
          )}
          {data.type === "warning" && (
            <React.Fragment>
              <WarningIcon />
              <p className="toast_msg_">{data?.msg}</p>
            </React.Fragment>
          )}
        </div>
      </div>
    ),
    {
      autoClose: interval,
    }
  );
};


export const CloseIcon = (props) => (
  <svg
    width={18}
    height={19}
    viewBox="0 0 18 19"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <circle cx={9} cy={9.00195} r={9} fill="#EC2120" />
    <path
      d="M6.00067 6.00391L12.0007 12.0039"
      stroke="white"
      strokeWidth={1.5}
      strokeLinecap="round"
    />
    <path
      d="M12.0005 6.00391L6.00049 12.0039"
      stroke="white"
      strokeWidth={1.5}
      strokeLinecap="round"
    />
  </svg>
);

export const TickIcon = (props) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 34 34"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    className="tickIcon"
    {...props}
  >
    <path
      d="M16.9997 0.333496C7.79967 0.333496 0.333008 7.80016 0.333008 17.0002C0.333008 26.2002 7.79967 33.6668 16.9997 33.6668C26.1997 33.6668 33.6663 26.2002 33.6663 17.0002C33.6663 7.80016 26.1997 0.333496 16.9997 0.333496ZM13.6663 25.3335L5.33301 17.0002L7.68301 14.6502L13.6663 20.6168L26.3163 7.96683L28.6663 10.3335L13.6663 25.3335Z"
      fill="#1EC003"
    />
  </svg>
);

export const WarningIcon = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={34}
    height={28.795}
    viewBox="0 0 34 28.795"
    {...props}
  >
    <path
      id="svgviewer-output_9_"
      data-name="svgviewer-output (9)"
      d="M33.653,29.2,18.667,4.982a1.854,1.854,0,0,0-3.272,0L.408,29.2c-.916,1.505,0,3.6,1.636,3.6H32.017C33.653,32.795,34.635,30.7,33.653,29.2ZM17.031,27.559A1.963,1.963,0,1,1,18.994,25.6,1.928,1.928,0,0,1,17.031,27.559Zm1.963-5.89a.618.618,0,0,1-.654.654H15.722a.618.618,0,0,1-.654-.654V13.162a.618.618,0,0,1,.654-.654H18.34a.618.618,0,0,1,.654.654Z"
      transform="translate(-0.045 -4)"
      fill="#FFAA00"
    />
  </svg>
);

